blank_issues_enabled: false
contact_links:
  - name: ✏️ FAQ
    url: https://www.youtube.com/channel/UCL8ssJ6dcCofNZvWowEzLRQ
    about: Procure no meu canal, perguntas e respostas sobre os problemas enfrentados por outros seguidores, talvez isso ajude a resolver seu problema tambem!.